version: '3.8'

services:
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: elephant-meal-app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    hostname: database_host
    environment:
      POSTGRES_DB: elephant-meal-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - /var/elephant-meal/postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: database_host
    ports:
      - "8080:8080"