"""Automatic migration

Revision ID: 05290a32aec0
Revises: 
Create Date: 2024-06-27 12:47:33.739904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05290a32aec0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_preferences', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('food_preferences', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_preferences', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('food_preferences', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
