"""Automatic migration

Revision ID: 1981c1f69c9c
Revises: 5b37b8aab247
Create Date: 2024-06-27 03:52:24.483992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1981c1f69c9c'
down_revision: Union[str, None] = '5b37b8aab247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('activity_type', sa.Enum('Sedentary_lifestyle', 'Light_activity', 'Moderate_activity', 'High_activity', 'Very_high_activity', name='activitytype'), nullable=False))
    op.drop_column('users', 'activity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity_type', postgresql.ENUM('Sedentary_lifestyle', 'Light_activity', 'Moderate_activity', 'High_activity', 'Very_high_activity', name='activitytype'), autoincrement=False, nullable=False))
    op.drop_column('plans', 'activity_type')
    # ### end Alembic commands ###
