"""Automatic migration

Revision ID: 2a17b2a758d9
Revises: ebe2e7598cee
Create Date: 2024-06-27 06:01:12.052049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a17b2a758d9'
down_revision: Union[str, None] = 'ebe2e7598cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'parent_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'parent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
