"""Automatic migration

Revision ID: 5055349c6be7
Revises: b00c55963f09
Create Date: 2024-06-27 08:10:36.882612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5055349c6be7'
down_revision: Union[str, None] = 'b00c55963f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_assortment', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_assortment', 'value')
    # ### end Alembic commands ###
