"""Automatic migration

Revision ID: 570f7dc09714
Revises: 1981c1f69c9c
Create Date: 2024-06-27 04:08:45.732098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570f7dc09714'
down_revision: Union[str, None] = '1981c1f69c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('utility', sa.Enum('Healthy', 'Normal', 'Unhealthy', name='utility'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'utility')
    # ### end Alembic commands ###
