"""Automatic migration

Revision ID: 5b37b8aab247
Revises: 
Create Date: 2024-06-27 03:33:19.544197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b37b8aab247'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity_type', sa.Enum('Sedentary_lifestyle', 'Light_activity', 'Moderate_activity', 'High_activity', 'Very_high_activity', name='activitytype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity_type')
    # ### end Alembic commands ###
