"""Automatic migration

Revision ID: 5b8a988daf8d
Revises: 
Create Date: 2024-06-27 11:47:12.624067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8a988daf8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('plans', sa.Column('start', sa.Date(), nullable=False))
    op.add_column('plans', sa.Column('end', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'end')
    op.drop_column('plans', 'start')
    op.alter_column('dishes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
