"""Automatic migration

Revision ID: d2d3574afcfd
Revises: ab8d60687f9d
Create Date: 2024-06-27 06:58:48.174692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d3574afcfd'
down_revision: Union[str, None] = 'ab8d60687f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredients_and_products', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients_and_products', type_='unique')
    # ### end Alembic commands ###
