"""Automatic migration

Revision ID: ef4389ea023a
Revises: 06382211551b
Create Date: 2024-06-27 07:29:12.633318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4389ea023a'
down_revision: Union[str, None] = '06382211551b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients_and_products', sa.Column('ingredient_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'ingredients_and_products', 'ingredients', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients_and_products', type_='foreignkey')
    op.drop_column('ingredients_and_products', 'ingredient_id')
    # ### end Alembic commands ###
