"""Automatic migration

Revision ID: f762378831f7
Revises: 570f7dc09714
Create Date: 2024-06-27 04:57:25.251955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f762378831f7'
down_revision: Union[str, None] = '570f7dc09714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_preferences', sa.Column('liked', sa.Boolean(), nullable=False))
    op.drop_column('food_preferences', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_preferences', sa.Column('name', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('food_preferences', 'liked')
    # ### end Alembic commands ###
