name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - deploy-test
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: deploy
      run: |
        ls