name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - deploy-test
    paths:
      - 'backend/**'
      - docker-compose.yml
      - Dockerfile
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: deploy
        run: docker compose up -d --build --force-recreate